
# MariaDB Setting , parameter store
spring.config.import=optional:aws-parameterstore:/config/mobinogi/spring/
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
server.port=${PORT}

# ssh tunnel setting
ssh.host=${SSH_HOST}
ssh.port=${SSH_PORT}
ssh.user=${SSH_USER}
ssh.privateKey=${SSH_PRIVATEKEY}
ssh.remoteHost=${SSH_REMOTEHOST}
ssh.remotePort=${SSH_REMOTEPORT}
ssh.localPort=${SSH_LOCALPORT}
ssh.keyPassphrase=${SSH_KEY_PASSPHRASE}

# conditional
device_id=${DEVICE_ID}

# chromeDriver path
webdriver.chrome.driver=${CHROMEDRIVER_PATH}

